# Generated by Django 2.2.4 on 2020-04-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_order_ordereditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordereditems',
            field=models.TextField(default='00'),
        ),
    ]
