# Generated by Django 2.2.4 on 2020-04-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_ordereditems'),
    ]

    operations = [
        migrations.CreateModel(
            name='phonenumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('phonenumber', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='phonenumber',
            field=models.TextField(default='00'),
        ),
    ]
