# Generated by Django 2.2.4 on 2020-04-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200417_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('message', models.TextField()),
                ('mobile', models.TextField()),
                ('dateofcontact', models.TextField()),
            ],
        ),
    ]
