# Generated by Django 2.2.4 on 2020-04-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contacted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Userid', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField()),
                ('phonenumber', models.TextField()),
                ('passcode', models.IntegerField()),
            ],
        ),
    ]
