# Generated by Django 2.2.4 on 2020-04-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200415_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailsCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderedby', models.TextField()),
                ('total_amount', models.TextField()),
                ('delivery_address', models.TextField()),
                ('Items', models.TextField()),
                ('Mobilenumber', models.TextField()),
            ],
        ),
    ]
