# Generated by Django 2.2.4 on 2020-04-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_accessusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(default='Davangere', max_length=100),
        ),
    ]
