# Generated by Django 2.2.4 on 2020-04-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orderdetailscheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.TextField(default='00'),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryaddress',
            field=models.TextField(default='00'),
        ),
    ]
