# Generated by Django 2.2.4 on 2020-04-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_billingaddress_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.FloatField(default=1),
        ),
    ]
