# Generated by Django 2.2.4 on 2020-04-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_usaorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPdummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField()),
                ('passcode', models.TextField()),
            ],
        ),
    ]
